blank_issues_enabled: false
contact_links:
  - name: Contato privado
    url: mailto:neurofilesaipro@hotmail.com
    about: Use para assuntos que contenham dados pessoais, licenças ou informações sensíveis.
